// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// generated by tools/build_glyphs.py, do not edit
library GlyphHashes {
    function hash(uint8 i) internal pure returns (bytes32) {
        if (i == 0) return 0xf846699d5f0a1cbf9e358da65175113aeab476615a9ee19f795223865a35d02a;
        if (i == 1) return 0x83c46f10e7e1b23df9f8dcb1b4b9d68650b89cf5890d1198aebe732138655e73;
        if (i == 2) return 0x1f1c7e10ebf198251918a3388fc010457936a5a448ed05ce3f4d6e6f63f22b2f;
        if (i == 3) return 0xe39db17274585e0c76007a7f9cc8acd2f9ea0267e6dddb3e66ba826dfa6ea243;
        if (i == 4) return 0x246c6f1951af4ba773c40a581613e16bf21af8227c0729925923666e8627859a;
        if (i == 5) return 0x487700569ca84f20eb0ca03853f9e151fa5289b065e2434ce60a387777af8dc3;
        revert();
    }
}
